version: "2"
services:
  node:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://test:test@postgres:5434/app_docker
      - TOKEN_SECRET=3ed2913ecaf9b6f90c7abe2024567d73
      - CLIENT_ID=232697356464615
      - FACEBOOK_APP_ID=232697356464615
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "run", "docker-dev"]
  postgres:
    image: postgres
    ports:
      - "5434:5432"
    volumes:
      - .data-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: app_docker
    restart: always

    networks:
      - mynetwork
networks:
  mynetwork:
